spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker123
  jpa:
    hibernate:
      ddl-auto: none
  #server:
 # port: 8181